// Auto generated by tools.
export default {
  definitions: {
    Accounts: {
      properties: {
        name: {
          example: "string",
          type: "string",
          description: "用户名",
        },
        email: {
          example: "string",
          type: "string",
          description: "email",
        },
        password: {
          example: "string",
          type: "string",
          description: "登录密码",
        },
        isActive: {
          example: false,
          type: "boolean",
          description: "是否激活",
        },
        isAdmin: {
          example: false,
          type: "boolean",
          description: "是否为超级管理员",
        },
      },
    },
  },
};
