// Auto generated by tools.
export default {
  definitions: {
    PDCAs: {
      properties: {
        startDate: {
          example: "string",
          type: "string",
          description: "PDCA开始日期; 日计划则为当日",
        },
        intro: {
          example: "string",
          type: "string",
          description: "任务说明",
        },
        tasks: {
          type: "array",
          description: "任务id清单",
          items: {
            taskId: {
              example: "string",
              type: "string",
              description: "任务id",
            },
            taskname: {
              example: "string",
              type: "string",
              description: "任务名称(加入PDCA时的名称，仅在任务删除后可使用此字段)",
            },
          },
        },
        check: {
          example: "string",
          type: "string",
          description: "检查",
        },
        act: {
          example: "string",
          type: "string",
          description: "总结",
        },
      },
    },
  },
};
