// Auto generated by tools.
export default {
  definitions: {
    Projects: {
      properties: {
        projectname: {
          example: "string",
          type: "string",
          description: "项目名称",
        },
        intro: {
          example: "string",
          type: "string",
          description: "项目说明",
        },
        group: {
          example: "b5a",
          type: "string",
          description: "分组",
        },
        status: {
          example: "open",
          type: "string",
          description: "项目状态",
        },
        parentId: {
          example: "string",
          type: "string",
          description: "父级项目",
        },
        bookId: {
          example: "string",
          type: "string",
          description: "Wiki书籍id",
        },
      },
    },
  },
};
