// Auto generated by tools.
export default {
  definitions: {
    Tasks: {
      properties: {
        taskname: {
          example: "string",
          type: "string",
          description: "任务名称",
        },
        intro: {
          example: "string",
          type: "string",
          description: "任务说明",
        },
        conclusion: {
          example: "string",
          type: "string",
          description: "任务结论",
        },
        status: {
          example: "open",
          type: "string",
          description: "任务状态",
        },
        isSettop: {
          example: "string",
          type: "string",
          description: "置顶时间戳",
        },
        frequency: {
          example: "once",
          type: "string",
          description: "任务频率",
        },
        day: {
          example: 100,
          type: "number",
          description: "weekly/monthly/annually时，表示第day日",
        },
        startDate: {
          example: "string",
          type: "string",
          description: "开始日期",
        },
        deadline: {
          example: "string",
          type: "string",
          description: "最迟结束日期",
        },
        realEndDate: {
          example: "string",
          type: "string",
          description: "实际结束日期",
        },
        progress: {
          example: 100,
          type: "number",
          description: "当前进度",
        },
        hours: {
          example: 100,
          type: "number",
          description: "计划耗时",
        },
        hoursLog: {
          type: "array",
          description: "耗时记录",
          items: {
            date: {
              example: "string",
              type: "string",
              description: "日期",
            },
            hours: {
              example: 100,
              type: "number",
              description: "耗时",
            },
            intro: {
              example: "string",
              type: "string",
              description: "说明",
            },
            progress: {
              example: 100,
              type: "number",
              description: "本次耗时到达的进度",
            },
          },
        },
        parentId: {
          example: "string",
          type: "string",
          description: "父级任务",
        },
        projectId: {
          example: "string",
          type: "string",
          description: "绑定项目",
        },
        articleId: {
          example: "string",
          type: "string",
          description: "绑定文章",
        },
        source: {
          example: "github",
          type: "string",
          description: "来源",
        },
        originalIssue: {
          example: "string",
          type: "string",
          description: "原始issue信息",
        },
      },
    },
  },
};
